// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Education: typeof import('./components/Education.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    Skills: typeof import('./components/Skills.vue')['default']
    Work: typeof import('./components/Work.vue')['default']
  }
}

export { }
